name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependency_overrides:
  analyzer: 6.5.0
  intl: 0.19.0
  meta: 1.14.0

dependencies:
  async: 2.11.0
  auto_route: ^8.1.3
  cached_network_image: 3.3.1
  flutter_cache_manager: ^3.3.2
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: 0.20.5
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  tuple: 2.0.2
  injectable: ^2.3.2
  # meta: 1.10.1
  rxdart: 0.27.7
  intl: 0.19.0
  intl_utils: 2.8.7
  mime: ^1.0.5
  package_info_plus: ^8.0.0
  device_info_plus: 10.1.2
  path_provider: ^2.1.1
  timezone: ^0.9.2
  url_launcher: ^6.2.4
  decimal: ^2.3.3
  connectivity_plus: 6.0.5
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  # gql: 0.14.0
  # gql_dio_link: 0.3.0
  # gql_exec: 0.4.3
  # gql_link: 0.5.1
  # graphql_flutter: 5.1.2v
  # location: 4.4.0 # ERROR: project ':location' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20

  fast_immutable_collections: ^10.1.1
  equatable: ^2.0.3 # Allows value based equality for our classes e.g Eat() == Eat() is true
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  # form_builder_phone_field: ^2.0.1
  android_id: 0.3.6
  flutter_udid: ^3.0.0
  # firebase
  firebase_auth: 5.2.1
  firebase_core: 3.4.1
  firebase_messaging: 15.1.1 # firebase_messaging-14.7.15\...\messaging\FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
  # firebase_dynamic_links: ^5.3.3
  firebase_analytics: 11.3.1
  firebase_crashlytics: 4.1.1
  firebase_remote_config: 5.1.1
  cloud_firestore: 5.4.1

  google_sign_in: ^6.1.0
  # flutter_facebook_auth: ^6.1.0
  shorebird_code_push: ^1.1.3

  # html: ^0.15.4
  encrypt: ^5.0.1
  permission_handler: ^11.3.0
  path: ^1.8.3
  # flutter_downloader: ^1.11.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  easy_debounce: ^2.0.3
  external_app_launcher: ^4.0.0 # open other app https://github.com/GeekyAnts/external_app_launcher/issues/26
  enum_to_string: ^2.0.1
  flutter_linkify: 6.0.0
  device_preview: 1.2.0
  country_pickers: 3.0.0 #fix: country_pickers-2.0.0 Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
  clock: 1.1.1
  app_links: 6.3.2

  # UI
  dynamic_color: ^1.6.6
  google_fonts: ^6.1.0
  animations: ^2.0.7
  simple_animations: ^5.0.2
  lottie: ^3.0.0
  pull_to_refresh: ^2.0.0
  another_flushbar: ^1.12.30
  flex_color_scheme: ^7.3.1
  google_nav_bar: ^5.0.6
  badges: ^3.1.2
  dropdown_button2: ^2.0.0
  chatview: 2.2.0
  popup_menu: 2.0.0
  settings_ui: 2.0.2
  flutter_slidable: 3.1.1

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: 2.4.7
  injectable_generator: ^2.4.1
  riverpod_generator: 2.4.0
  riverpod_analyzer_utils: 0.5.1
  riverpod_lint: 2.3.10
  custom_lint: 0.6.4
  custom_lint_builder: 0.6.4
  flutter_gen_runner: 5.4.0
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  flutter_native_splash: 2.3.10
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  mocktail: ^1.0.3
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1
  # leancode_lint: ^13.0.0
  golden_toolkit: 0.15.0

# Config generate when build
flutter_gen:
  output: lib/resources/generated
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true

flutter:
  uses-material-design: true
  # generate: false
  assets:
    - assets/images/
    - shorebird.yaml
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/resources/generated
  arb_dir: lib/resources/l10n
# objectbox:
#   output_dir: data/database/generated
