flutter_launcher_icons:
  android: true
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/images/android_app_icon.png"
  ios: true
  image_path: "assets/images/app_icon.png"
  # image_path_android: "assets/images/ios_app_icon.png"
  # image_path_ios: "assets/images/ios_app_icon.png"
