import 'dart:math';

class AppUtils {
  const AppUtils._();
  static String randomName() {
    final _random = Random();

    const _names = [
      'Dog',
      'Cat',
      'Elephant',
      'Lion',
      'Tiger',
      'Giraffe',
      'Zebra',
      'Bear',
      'Monkey',
      'Horse',
      'Cow',
      'Sheep',
      'Goat',
      'Pig',
      'Rabbit',
      'Deer',
      'Fox',
      'Wolf',
      'Kangaroo',
      'Panda',
      'Dolphin',
      'Whale',
      'Shark',
      'Octopus',
      'Penguin',
      'Seal',
      'Otter',
      'Walrus',
      'Bat',
      'Squirrel',
      'Chipmunk',
      'Raccoon',
      'Beaver',
      'Koala',
      'Platypus',
      'Ostrich',
      'Emu',
      'Parrot',
      'Toucan',
      'Pelican',
      'Hummingbird',
      'Eagle',
      'Hawk',
      'Falcon',
      'Owl',
      'Sparrow',
      'Crow',
      'Swan',
      'Flamingo',
      'Heron',
      'Peacock',
      'Pigeon',
      'Seagull',
      'Albatross',
      'Cockatoo',
      'Macaw',
      'Cockroach',
      'Grasshopper',
      'Ant',
      'Bee',
      'Wasp',
      'Butterfly',
      'Moth',
      'Caterpillar',
      'Dragonfly',
      'Ladybird',
      'Beetle',
      'Scorpion',
      'Spider',
      'Tarantula',
      'Centipede',
      'Millipede',
      'Earthworm',
      'Slug',
      'Snail',
      'Jellyfish',
      'Starfish',
      'Crab',
      'Lobster',
      'Shrimp',
    ];

    return '${_names[_random.nextInt(_names.length)]}${_random.nextInt(100)}';
  }
}
